<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1

| Term | Brief Description|
|------|--------------|
|Subsetting|To pick only some elements or part of the data |
|Indexing |To select using the index number of the element in the list |
|Masking| To select only elements in an array that fulfil the criteria |

## Exercise 2

In [11]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
numbers_array = np_array_2d[:,0]
numbers_mask = numbers_array.astype(int)%2 !=0
letters_array = np_array_2d[numbers_mask]
letters_array[:,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

## Exercise 3

In [41]:
import numpy as np
numbers= [[66, 50, 57, -1, -1],
                         [92, -1, 88, -1, -1],
                         [75, -1, -1, 76, -1],
                         [-1, 51, 87, -1, -1],
                         [71, -1, 67, -1, 69]]
np_array = np.array(numbers)
np_array[np_array < 50] = -1
np_array[np_array > 50] = 1
np_array[np_array == 50] = 0
print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
