<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

## 1.3 Accessing data from a dictionary

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

## 2.1 Size

In [5]:
import numpy as np
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
print(np_array_2d)
np_array_2d.shape #the length and width of the array

[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']
 ['6' 'F']
 ['7' 'G']
 ['8' 'H']
 ['9' 'I']
 ['10' 'J']]


(10, 2)

## 2.2 Arrays are fussy about type

arrays only accept values of same type

## 2.3 Adding a number

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)  
np_array + 10 # adds 10 to all values in array
print(np_array + 10)

[11 12 13 14 15]


## 2.4 Adding another list

In [ ]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(py_list_1 + py_list_2) #combines elements in both list literally
np_array_1 + np_array_2 #adds values of elements in both arrays

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [14]:
print(np_array*2)
py_list*2

[ 2  4  6  8 10]


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

## 2.6 Squaring

## 2.7 Asking questions

In [18]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)   
np_array > 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

## Footnotes